FROM ubuntu:jammy-20220531
RUN apt update
RUN apt install -y gcc g++ gfortran libblas-dev liblapack-dev cmake git ccache rsync curl bash doxygen graphviz libopenblas-dev liblapacke-dev pkg-config mpich-dev
