name: Build doxygen pages and publish to github pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --target DependencyManagerDocs
          rsync -a ${{github.workspace}}/build/docs/utilities/html .
          cp ${{github.workspace}}/build/docs/utilities/utilities.tag ./html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
