name: Build doxygen pages and publish to github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Doxygen
        run: |
          PUBLIC=./public
          mkdir -p $PUBLIC && touch $PUBLIC/.thing
          echo '<html> <head> </head> <body> <h1>Hello World<h1> <p>Hello World!!</p> </body> </html>' > $PUBLIC/index.html
          pwd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public