name: Build doxygen pages and publish to github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --target DependencyManagerDocs
          echo directory=${{github.workspace}}/build
          ls -ltRa ${{github.workspace}}/build

#      - name: Doxygen
#        run: |
#          PUBLIC=./public
#          mkdir -p $PUBLIC && touch $PUBLIC/.thing
#          echo '<html> <head> </head> <body> <h1>Hello World<h1> <p>Hello World!!</p> </body> </html>' > $PUBLIC/index.html
#          pwd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/build/docs/utilities/html